---
title: "Full object subsetting"
output:
  html_document:
    df_print: paged    
    toc: TRUE

---

```{css, echo=FALSE}
img {
  max-width:150%;
  height: auto;
}
```

```{r call-libraries} 
library(Giotto)
library(future); if(parallelly::availableCores() > 2 & .Platform$OS.type == "windows")  
  {plan('multisession', workers = parallelly::availableCores()-2)}
options(future.globals.maxSize= 1e12)
library(scran); library(MAST); library(leiden);    
library(data.table)
library(gplots); library(ggplot2); library(viridis)
library(dbscan)
library(dplyr); library(leidenAlg)
set.seed(43)
knitr::opts_chunk$set(fig.retina = 2)
sessionInfo()

```

```{r readRDS-sln-harmony}
sln <- readRDS("sln.harmony.RDS")

```



```{r merge-metadata}
# meta <- fread("../../../Downloads/sln.metadata.csv")                   # executed just one time 
# df <- unique(meta, by = c("sample"))
# df <- df[, list(orig.ident,SLN_Stage,`Path Accession Number`,SLN_Biopsy, SLN_Biopsy_Date, Sex,Age,SLN_Area, Tumor_Area, `Tumor_Greatest_Dimension(mm)`, Histology, `Primary_Breslow(mm)`, Tumor_Infiltrating_Lymphocytes, `Mitoses(mm^2)`, Ulceration, Recurrence, Recurrence_Date, Months_To_Recurrence, Raw_Recur_Group, Death, Chemotherapy_Treatment, Chemotherapy_Treatment_Type, Immunotherapy_Treatment, Immunotherapy_Treatment_Date,Immunotherapy_Treatment_Type)]
# write.csv(df, "sln.metadata.csv")

md <- pDataDT(sln)
df <- fread("sln.metadata.csv", na.strings = "N/A")
df$list_ID <- c("ctrl.1","ctrl.2","ctrl.3","ctrl.4","ctrl.5","tumor.1", "tumor.2", "tumor.3","tumor.4", "tumor.5", 
                "tumor.6", "tumor.7", "tumor.8", "tumor.9", "tumor.10")
setcolorder(df, colnames(df)[c(27, 2:26) ]);  df$V1 <- NULL   # clean up column names & order of columns 
a <- as.data.frame(table(md$list_ID))        # how many rows are there per sample, but this orders the result before returning
b <- unique(md$list_ID)                      # this will give the correct order of appearance in the table
a <- a[match(b, a$Var1), ]                    # give the table in order
toChange <- names(df)[c(9:11,14:15, 19, 21)]  # have to turn these from char to numeric or later plots will all break
for (i in toChange) {  df[, (i) := as.numeric(get(i))]  }   # change columns to numeric
df <- df[match(b, df$list_ID), ]              # reorder df to be in the right order 
names(df)[11] <- 'Tum_Gr_Dim'                 # column 11 is a problem!!! only works if the name is way shorter
new_metadata<- df[rep(1:nrow(df), times = a$Freq), ]  # repeat rows the right number of times
md <- cbind(cell_ID=md$cell_ID, new_metadata )        # now this is ok  
sln <- addCellMetadata(gobject = sln, new_metadata = md, by_column=T, column_cell_ID = 'cell_ID')

rm(new_metadata); rm(a); rm(b)
md <- pDataDT(sln); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e4))$cell_ID
sln.sm <- subsetGiotto(gobject = sln, cell_ids = keepCells)
leiden_colors <- getDistinctColors(length(unique(md$trnsfr_leiden_harmony)))
names(leiden_colors) <- unique(md$trnsfr_leiden_harmony)
plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'trnsfr_leiden_harmony',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.75, point_shape="no_border",
         point_alpha=0.5)
```


```{r save-sln-meta}
saveRDS(sln, "sln.harmony.meta.RDS")
```

