---
title: "Clustering part 4"
output:
  html_document:
    df_print: paged    
    toc: TRUE
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
---

```{css, echo=FALSE}
img {
  max-width:150%;
  height: auto;
}
```

```{r call-libraries} 
date()
library(Giotto)
library(future); if(parallelly::availableCores() > 2 & .Platform$OS.type == "windows")  
  {plan('multisession', workers = parallelly::availableCores()-2)}
options(future.globals.maxSize= 1e12)
library(scran); library(MAST); library(leiden);    
library(data.table)
library(gplots); library(ggplot2); library(viridis)
library(dbscan)
library(dplyr); library(leidenAlg)
set.seed(43)
knitr::opts_chunk$set(fig.retina = 2)
sessionInfo()

```

```{r readRDS-clustering3}
sln <- readRDS("sln.clustering3.dim5k15.res0.7.20250418.091140.RDS")
print(paste("Primary object size: ", length(sln@cell_ID$cell), "cells"))
md <- pDataDT(sln) 
print("cluster membership")
print(table(md$leiden_harmony))
print(table(md$L1_annotations))
```


```{r assign_newLabels}
df <- data.frame(leiden.clust3.r0.7 = md$leiden.clust3.r0.7, L2_annotations = "Unknown")
df$cell_ID <- md$cell_ID
df$L2_annotations <- paste0("Clust.", df$leiden.clust3.r0.7)  # unknown clusters:
df[which(df$leiden.clust3.r0.7  == "1" ), 'L2_annotations'] <-  "TBMixed.1"
df[which(df$leiden.clust3.r0.7  == "2" ), 'L2_annotations'] <-  "TBMixed.2"
df[which(df$leiden.clust3.r0.7  == "3" ), 'L2_annotations'] <-  "TBMixed.3"
df[which(df$leiden.clust3.r0.7  == "4" ), 'L2_annotations'] <-  "TBMixed.4"
df[which(df$leiden.clust3.r0.7  == "5" ), 'L2_annotations'] <-  "BCells.1"
df[which(df$leiden.clust3.r0.7  == "6" ), 'L2_annotations'] <-  "TBMixed.5"
df[which(df$leiden.clust3.r0.7  == "7" ), 'L2_annotations'] <-  "BCells.2"
df[which(df$leiden.clust3.r0.7  == "8" ), 'L2_annotations'] <-  "TCells.1"
df[which(df$leiden.clust3.r0.7  == "9" ), 'L2_annotations'] <-  "BCells.3"
df[which(df$leiden.clust3.r0.7  == "10" ), 'L2_annotations'] <-  "TCells.2"
df[which(df$leiden.clust3.r0.7  == "11" ), 'L2_annotations'] <-  "TBMixed.6"
df[which(df$leiden.clust3.r0.7  == "12" ), 'L2_annotations'] <-  "TBMixed.7"
df[which(df$leiden.clust3.r0.7  == "13" ), 'L2_annotations'] <-  "TBMixed.8"
df[which(df$leiden.clust3.r0.7  == "14" ), 'L2_annotations'] <-  "TBMixed.9"
df[which(df$leiden.clust3.r0.7  == "15" ), 'L2_annotations'] <-  "TBMixed.10"
df[which(df$leiden.clust3.r0.7  == "16" ), 'L2_annotations'] <-  "TBMixed.11"
df[which(df$leiden.clust3.r0.7  == "17" ), 'L2_annotations'] <-  "TCells.3"
df[which(df$leiden.clust3.r0.7  == "18" ), 'L2_annotations'] <-  "TCells.4"
df[which(df$leiden.clust3.r0.7  == "19" ), 'L2_annotations'] <-  "TCells.5"
df[which(df$leiden.clust3.r0.7  == "20" ), 'L2_annotations'] <-  "TCells.6"
df[which(df$leiden.clust3.r0.7  == "21" ), 'L2_annotations'] <-  "TCells.7"
df[which(df$leiden.clust3.r0.7  == "22" ), 'L2_annotations'] <-  "TCells.8"
df[which(df$leiden.clust3.r0.7  == "23" ), 'L2_annotations'] <-  "TCells.9"
df[which(df$leiden.clust3.r0.7  == "24" ), 'L2_annotations'] <-  "TCells.10"
df[which(df$leiden.clust3.r0.7  == "25" ), 'L2_annotations'] <-  "TCells.11"
df[which(df$leiden.clust3.r0.7  == "26" ), 'L2_annotations'] <-  "BCells.4"
df[which(df$leiden.clust3.r0.7  == "27" ), 'L2_annotations'] <-  "TBMixed.12"
df[which(df$leiden.clust3.r0.7  == "28" ), 'L2_annotations'] <-  "TBMixed.13"
df[which(df$leiden.clust3.r0.7  == "29" ), 'L2_annotations'] <-  "BCells.5"
df[which(df$leiden.clust3.r0.7  == "30" ), 'L2_annotations'] <-  "TBMixed.14"
df[which(df$leiden.clust3.r0.7  == "31" ), 'L2_annotations'] <-  "TCells.12"
df[which(df$leiden.clust3.r0.7  == "32" ), 'L2_annotations'] <-  "BCells.6"
df[which(df$leiden.clust3.r0.7  == "33" ), 'L2_annotations'] <-  "TCells.13"
df[which(df$leiden.clust3.r0.7  == "34" ), 'L2_annotations'] <-  "TCells.14"
df[which(df$leiden.clust3.r0.7  == "35" ), 'L2_annotations'] <-  "BCells.7"
df[which(df$leiden.clust3.r0.7  == "36" ), 'L2_annotations'] <-  "BCells.8"
df[which(df$leiden.clust3.r0.7  == "37" ), 'L2_annotations'] <-  "TBMixed.15"
df[which(df$leiden.clust3.r0.7  == "38" ), 'L2_annotations'] <-  "TBMixed.16"
df[which(df$leiden.clust3.r0.7  == "39" ), 'L2_annotations'] <-  "TBMixed.17"
df[which(df$leiden.clust3.r0.7  == "40" ), 'L2_annotations'] <-  "TBMixed.18"
df[which(df$leiden.clust3.r0.7  == "41" ), 'L2_annotations'] <-  "TBMixed.19"
df[which(df$leiden.clust3.r0.7  == "42" ), 'L2_annotations'] <-  "BCells.9"
df[which(df$leiden.clust3.r0.7  == "43" ), 'L2_annotations'] <-  "TCells.15"
df[which(df$leiden.clust3.r0.7  == "44" ), 'L2_annotations'] <-  "TCells.16"
df[which(df$leiden.clust3.r0.7  == "45" ), 'L2_annotations'] <-  "TBMixed.20"
df[which(df$leiden.clust3.r0.7  == "46" ), 'L2_annotations'] <-  "BCells.10"
df[which(df$leiden.clust3.r0.7  == "47" ), 'L2_annotations'] <-  "TCells.17"
df[which(df$leiden.clust3.r0.7  == "48" ), 'L2_annotations'] <-  "TCells.18"
df[which(df$leiden.clust3.r0.7  == "49" ), 'L2_annotations'] <-  "BCells.11"
df[which(df$leiden.clust3.r0.7  == "50" ), 'L2_annotations'] <-  "TCells.19"
df[which(df$leiden.clust3.r0.7  == "51" ), 'L2_annotations'] <-  "BCells.12"
df[which(df$leiden.clust3.r0.7  == "52" ), 'L2_annotations'] <-  "BCells.13"
df[which(df$leiden.clust3.r0.7  == "53" ), 'L2_annotations'] <-  "TBMixed.21"
df[which(df$leiden.clust3.r0.7  == "54" ), 'L2_annotations'] <-  "BCells.14"
df[which(df$leiden.clust3.r0.7  == "55" ), 'L2_annotations'] <-  "BCells.15"
df[which(df$leiden.clust3.r0.7  == "56" ), 'L2_annotations'] <-  "TCells.20"
df[which(df$leiden.clust3.r0.7  == "57" ), 'L2_annotations'] <-  "TCells.21"
df[which(df$leiden.clust3.r0.7  == "58" ), 'L2_annotations'] <-  "TCells.22"
df[which(df$leiden.clust3.r0.7  == "59" ), 'L2_annotations'] <-  "TBMixed.22"
df[which(df$leiden.clust3.r0.7  == "60" ), 'L2_annotations'] <-  "TBMixed.23"
df[which(df$leiden.clust3.r0.7  == "61" ), 'L2_annotations'] <-  "TCells.23"
df[which(df$leiden.clust3.r0.7  == "62" ), 'L2_annotations'] <-  "TBMixed.24"
df[which(df$leiden.clust3.r0.7  == "63" ), 'L2_annotations'] <-  "TBMixed.25"
df[which(df$leiden.clust3.r0.7  == "64" ), 'L2_annotations'] <-  "BCells.16"
df <- md[,c("cell_ID","L2_annotations")]
sln <- addCellMetadata(gobject = sln, new_metadata = df, by_column=T, column_cell_ID = 'cell_ID')
rm(df)

```


# calculate T cell subsets
```{r subset-T-cells}
gc()
md <- pDataDT(sln); keepCells <- md$cell_ID[which(md$L1.annot == "Tcells")]
Tcells <- subsetGiotto(sln, cell_ids = keepCells )
print("recalculate clusters post-exclusion")
clusterChannels <- c("CD3E", "CD4", "CD8", "TCF1", "GZMB", "CD39", "KI67", "PD1", "TOX", "FOXP3", "ICOS", "CD45RA","HLA.DR")
Tcells <- runPCA(gobject = Tcells, expression_values = "normalized", scale_unit = TRUE, 
              method = "factominer", feats_to_use = clusterChannels)
signPCA(Tcells, scale_unit = TRUE, scree_ylim = c(0,40))
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = sample(sln$cell_ID, 1e5, replace=F)) # make a smaller dataset to work with 
sln.sm <- createNearestNetwork(gobject = sln.sm, dim_reduction_to_use = 'harmony', dim_reduction_name = 'harmony', 
                            name = 'NN.harmony', dimensions_to_use = 1:10, k = 10)  # calculate nearest neighbors, focus on global differences 
sln.sm <- doLeidenClusterIgraph(gobject = sln.sm, resolution = 0.3, n_iterations = 100, set_seed = T, seed_number = 43,
                                network_name = 'NN.harmony', name = 'leiden_Tcells')  # make the clusters
Tcells <- labelTransfer(x = Tcells, y = sln.sm, labels = "leiden_Tcells")  # assign cluster labels in the full dataset based on the reduced data
Tcells <- runUMAPprojection(Tcells, random_subset = 1e5)  # project UMAP coordinates to the full dataset based on a subsampling
saveRDS(Tcells, "Tcells.RDS")
```


```{r readRDS-harmony-excl-annot}
Tcells <- readRDS("Tcells.RDS")
plots <- list()
```


```{r readRDS-harmony-Tcells}
Tcells <- readRDS("Tcells.RDS")
plots <- list()
```




```{r plot-UMAP-heatmap-Tcells, fig.show="hold", out.width="50%"}
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 5e5))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
leiden_colors <- getDistinctColors(length(unique(md$trnsfr_leiden_Tcells)))
names(leiden_colors) <- unique(md$trnsfr_leiden_Tcells)
plots[[1]] <- plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'trnsfr_leiden_Tcells',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.75, point_shape="no_border",
         point_alpha=0.5, return_plot=T)

# markers_scran <- findMarkers_one_vs_all(gobject = Tcells, method = "scran", expression_values = "normalized",
#                                         cluster_column = "trnsfr_leiden_harmony", min_feats = 3)
# 
# topgenes_scran <- unique(markers_scran[, head(.SD, 5), by = "cluster"][["feats"]])

clusterChannels <- c("CD3E", "CD4", "CD8", "TCF1", "GZMB", "CD39", "KI67", "PD1", "TOX", "FOXP3", "ICOS")

plots[[2]] <- plotMetaDataHeatmap(Tcells, expression_values = "normalized",
                    metadata_cols = "trnsfr_leiden_Tcells", selected_feats = clusterChannels,
                    y_text_size = 8, show_values = "zscores_rescaled", return_plot = T)
```


```{r spatDimPlot-Tcells, fig.width=12, fig.height=12}
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e5))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
plots[[3]] <- dimFeatPlot2D(sln.sm, dim_reduction_name = 'umap.projection', expression_values = "scaled", 
              feats = c("TCF1","TOX", "CD8", "CD4","FOXP3","ICOS"), 
              point_alpha = 0.2, point_shape = "no_border", cow_n_col = 2, return_plot=T)
```


```{r show-violin, fig.show="hold", fig.width=5, fig.height=10, warning=F}
# don't try to do violinplot on more than 100k cells! 
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 5e4))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
violinPlot(sln.sm, feats = clusterChannels, cluster_column = "trnsfr_leiden_Tcells")

```


```{r plot-joined-plots-2}
if(.Platform$OS.type == "windows")  # only try to plot this if we're not in Windows (so presumably on HPC)
{  
  plt <- gridExtra::grid.arrange(grobs = list(plots[[1]], plots[[2]],plots[[3]]),
                        layout_matrix = rbind(c(1,1,2,2,2),
                                              c(3,3,3,3,4),
                                              c(3,3,3,3,5)))
  ggsave(plot=plt,filename = "annotation_Tcells.png",height = 15,width=10)
  # ggsave(plot=plots[[4]],filename="tumor.5.clusters.pdf",height=14,width=10)
  plt; rm(plt)
}
```




```{r label-L2annotation}
md <- pDataDT(Tcells)
df <- data.frame(trnsfr_leiden_Tcells = md$trnsfr_leiden_Tcells, L2.annot = "Unknown")
df$cell_ID <- md$cell_ID
df$L2.annot <- paste0("Tcells.", df$trnsfr_leiden_Tcells)  # unknown clusters:  1,2,3,5,7,8,9,11,21
df[which(df$trnsfr_leiden_Tcells %in% c(4)), 'L2.annot'] <- "CD8.1"
df[which(df$trnsfr_leiden_Tcells %in% c(6)), 'L2.annot'] <- "CD8.2"
df[which(df$trnsfr_leiden_Tcells %in% c(10)), 'L2.annot']  <- "CD8.3"
df[which(df$trnsfr_leiden_Tcells %in% c(12)), 'L2.annot'] <- "CD4.1"
df[which(df$trnsfr_leiden_Tcells %in% c(13)), 'L2.annot'] <- "Treg.1"
df[which(df$trnsfr_leiden_Tcells %in% c(14)), 'L2.annot'] <- "CD4.2"
df[which(df$trnsfr_leiden_Tcells %in% c(15)), 'L2.annot'] <- "CD4.3"
df[which(df$trnsfr_leiden_Tcells %in% c(16)), 'L2.annot'] <- "CD4.4"
df[which(df$trnsfr_leiden_Tcells %in% c(17)), 'L2.annot'] <- "CD4.5"
df[which(df$trnsfr_leiden_Tcells %in% c(18)), 'L2.annot'] <- "CD4.6"
df[which(df$trnsfr_leiden_Tcells %in% c(19)), 'L2.annot'] <- "CD4.6"
df[which(df$trnsfr_leiden_Tcells %in% c(20)), 'L2.annot'] <- "CD8.4"
df$trnsfr_leiden_Tcells <- NULL

Tcells <- addCellMetadata(Tcells, new_metadata = df, by_column = T, column_cell_ID="cell_ID")  # add in the annotations to the main object

md <- pDataDT(Tcells)
keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e5))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
leiden_colors <- getDistinctColors(length(unique(md$L2.annot)))
names(leiden_colors) <- unique(md$L2.annot)
plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'L2.annot',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.5, point_shape="no_border",
         point_alpha=0.35)

```


```{r readRDS-harmony-excl-annot}
sln <- readRDS("sln.harmony.excl.annot.RDS")
plots <- list()
```


```{r merge-in-Tcell-annotations, fig.show="hold", out.width="50%"}
md.sln <- pDataDT(sln)
md.T <- pDataDT(Tcells)
md.sln$L2.annot <- "N/A"
md.sln$L2.annot[which(md.sln$cell_ID %in% md.T$cell_ID)] <- md.T$L2.annot
table(md.sln$L2.annot, useNA="ifany")
df <- md.sln[,c("cell_ID","L2.annot")]
sln <- addCellMetadata(sln, new_metadata = df, by_column = T, column_cell_ID="cell_ID")  # add in the annotations to the main object
rm(md.sln)
rm(md.T)

md <- pDataDT(sln)
keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e5))$cell_ID
sln.sm <- subsetGiotto(gobject = sln, cell_ids = keepCells)
leiden_colors <- getDistinctColors(length(unique(md$L1.annot)))
names(leiden_colors) <- unique(md$L1.annot)
plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'L1.annot',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.5, point_shape="no_border",
         point_alpha=0.35)

leiden_colors <- getDistinctColors(length(unique(md$L2.annot)))
names(leiden_colors) <- unique(md$L2.annot)
plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'L2.annot',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.5, point_shape="no_border",
         point_alpha=0.35)

```


```{r writeRDS-sln-Tcell-annot}
md <- pDataDT(sln)
table(md$L1.annot)
table(md$L2.annot)

filename <- paste0("sln.L2.annot.",  strftime(Sys.time() , "%Y%m%d.%H%M%S"), ".RDS")
saveRDS(sln, filename)
```



```{r call-date}
date()
```
















