---
title: "Clustering part 3"
output:
  html_document:
    df_print: paged    
    toc: TRUE

---

```{css, echo=FALSE}
img {
  max-width:150%;
  height: auto;
}
```

```{r call-libraries} 
library(Giotto)
library(future); if(parallelly::availableCores() > 2 & .Platform$OS.type == "windows")  
  {plan('multisession', workers = parallelly::availableCores()-2)}
options(future.globals.maxSize= 1e12)
library(scran); library(MAST); library(leiden);    
library(data.table)
library(gplots); library(ggplot2); library(viridis)
library(dbscan)
library(dplyr); library(leidenAlg)
set.seed(43)
knitr::opts_chunk$set(fig.retina = 2)
sessionInfo()

```



```{r readRDS-harmony-excl-annot}

sln <- readRDS("sln.harmony.excl.annot.RDS")
plots <- list()
```


```{r subset-T-cells}
gc()
md <- pDataDT(sln); keepCells <- md$cell_ID[which(md$L1.annot == "Tcells")]
Tcells <- subsetGiotto(sln, cell_ids = keepCells )

sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = sample(sln$cell_ID, 1e5, replace=F)) # make a smaller dataset to work with 
sln.sm <- createNearestNetwork(gobject = sln.sm, dim_reduction_to_use = 'harmony', dim_reduction_name = 'harmony', 
                            name = 'NN.harmony', dimensions_to_use = 1:10, k = 10)  # calculate nearest neighbors, focus on global differences 
sln.sm <- doLeidenClusterIgraph(gobject = sln.sm, resolution = 0.3, n_iterations = 100, set_seed = T, seed_number = 43,
                                network_name = 'NN.harmony', name = 'leiden_Tcells')  # make the clusters
Tcells <- labelTransfer(x = Tcells, y = sln.sm, labels = "leiden_Tcells")  # assign cluster labels in the full dataset based on the reduced data
Tcells <- runUMAPprojection(Tcells, random_subset = 1e5)  # project UMAP coordinates to the full dataset based on a subsampling
saveRDS(Tcells, "Tcells.RDS")
```





```{r plot-UMAP-heatmap-Tcells, fig.show="hold", out.width="50%"}
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 5e5))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
leiden_colors <- getDistinctColors(length(unique(md$trnsfr_leiden_Tcells)))
names(leiden_colors) <- unique(md$trnsfr_leiden_Tcells)
plots[[1]] <- plotUMAP(gobject = sln.sm, dim_reduction_name = 'umap.projection', cell_color = 'trnsfr_leiden_Tcells',
         cell_color_code = leiden_colors, show_NN_network = F, point_size = 0.75, point_shape="no_border",
         point_alpha=0.5, return_plot=T)

# markers_scran <- findMarkers_one_vs_all(gobject = Tcells, method = "scran", expression_values = "normalized",
#                                         cluster_column = "trnsfr_leiden_harmony", min_feats = 3)
# 
# topgenes_scran <- unique(markers_scran[, head(.SD, 5), by = "cluster"][["feats"]])

clusterChannels <- c("CD3E", "CD4", "CD8", "TCF1", "GZMB", "CD39", "KI67", "PD1", "TOX", "FOXP3", "ICOS")

plots[[2]] <- plotMetaDataHeatmap(Tcells, expression_values = "normalized",
                    metadata_cols = "trnsfr_leiden_Tcells", selected_feats = clusterChannels,
                    y_text_size = 8, show_values = "zscores_rescaled", return_plot = T)
```
```{r spatDimPlot-Tcells, fig.width=12, fig.height=12}
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e5))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
plots[[3]] <- dimFeatPlot2D(sln.sm, dim_reduction_name = 'umap.projection', expression_values = "scaled", 
              feats = c("TCF1","TOX", "CD8", "PD1","FOXP3","ICOS"), 
              point_alpha = 0.2, point_shape = "no_border", cow_n_col = 2, return_plot=T)
```


```{r show-violin, fig.show="hold", fig.width=5, fig.height=10, warning=F}
# don't try to do violinplot on more than 100k cells! 
md <- pDataDT(Tcells); keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 5e4))$cell_ID
sln.sm <- subsetGiotto(gobject = Tcells, cell_ids = keepCells)
violinPlot(sln.sm, feats = clusterChannels, cluster_column = "trnsfr_leiden_Tcells")

```


