---
title: "Neighborhood analyses"
output:
  html_document:
    df_print: paged    
    toc: TRUE
---
 

```{css, echo=FALSE}
img {
  max-width:150%;
  height: auto;
}
```
 
 
```{r call-libraries} 
date()
library(Giotto)
library(future); if(parallelly::availableCores() > 2 & .Platform$OS.type == "windows")  
  {plan('multisession', workers = parallelly::availableCores()-2)}
options(future.globals.maxSize= 1e12)
library(scran); library(MAST); library(leiden);   # library(multinet);  
library(data.table)
library(gplots); library(ggplot2); library(viridis)
library(dbscan)
library(dplyr); library(leidenAlg)
set.seed(43)
sessionInfo()
```

# read in data object 
```{r read-in-data}
sln <- readRDS("sln.clustering2.res0.3.20250411.1442.RDS")
plots = list()
prox.results = list()
```

# calculate cellProximityEnrichment 
```{r cellProximityEnrichment}
md <- pDataDT(sln)
list_ID <- unique(md$list_ID)
gc()

for (i in list_ID[1:2])
{
  print(i)
  keepCells <- subset(md, list_ID %in% i )$cell_ID
  sln.sm <- subsetGiotto(gobject = sln, cell_ids = keepCells)
  sln.sm <- createSpatialKNNnetwork(sln.sm) 
  
  prox.results[i] <- cellProximityEnrichment(sln.sm, cluster_column = 'leiden_harmony', adjust_method = "fdr",
                                      number_of_simulations = 200, spatial_network_name = "knn_network")
  # Barplot depicting the ratio of observed over expected frequencies of pairwise interacting clusters (left). Barplot showing the total number of interactions between each pair (right).
  
  plots[i] <- cellProximityBarplot(sln.sm, CPscore = prox.results[i],  min_orig_ints = 3, min_sim_ints = 3, return_plot = T)
}

```




# interaction changed genes
```{r Interaction-changed-genes, eval=FALSE, echo=FALSE}
gene_metadata = fDataDT(sln.sm)

high_expressed_genes = gene_metadata[mean_expr_det > quantile(gene_metadata$mean_expr_det)[4]]$gene_ID

## identify genes that are associated with proximity to other cell types
ICGscoresHighGenes = findInteractionChangedFeats(gobject = sln.sm, selected_feats = high_expressed_genes,
                                                 spatial_network_name = "knn_network", cluster_column = 'L1.annot',
                                                 diff_test = 'permutation', adjust_method = 'fdr', 
                                                 nr_permutations = 20, do_parallel = FALSE)
## visualize
plotCellProximityGenes(sln.sm, cpgObject = ICGscoresHighGenes, method = 'dotplot')
```


# try a customized version of cellProxEnrich
```{r custom-cellproxEnrich-function}
cellProxEnrich.cust <- function(gobject,
    spat_unit = NULL,
    feat_type = NULL,
    spatial_network_name = "Delaunay_network",
    cluster_column,
    number_of_simulations = 1000,
    adjust_method = c(
        "none", "fdr", "bonferroni", "BH",
        "holm", "hochberg", "hommel",
        "BY"
    ),
    set_seed = TRUE,
    seed_number = 1234) 
{
    # Set feat_type and spat_unit
    spat_unit <- set_default_spat_unit(
        gobject = gobject,
        spat_unit = spat_unit
    )
    feat_type <- set_default_feat_type(
        gobject = gobject,
        spat_unit = spat_unit,
        feat_type = feat_type
    )

    # p.adj test
    sel_adjust_method <- match.arg(adjust_method, choices = c(
        "none", "fdr", "bonferroni", "BH",
        "holm", "hochberg", "hommel",
        "BY"
    ))

    spatial_network_annot <- annotateSpatialNetwork(
        gobject = gobject,
        feat_type = feat_type,
        spat_unit = spat_unit,
        spatial_network_name = spatial_network_name,
        cluster_column = cluster_column
    )

    # remove double edges between same cells #
    # a simplified network does not have double edges between cells #

    # data.table variables
    unified_cells <- type_int <- N <- NULL

    spatial_network_annot <- GiottoUtils:::dt_sort_combine_two_columns(
        spatial_network_annot, "to", "from", "unified_cells"
    )
    spatial_network_annot <- spatial_network_annot[!duplicated(unified_cells)]

    sample_dt <- Giotto:::make_simulated_network(
        gobject = gobject,
        spat_unit = spat_unit,
        feat_type = feat_type,
        spatial_network_name = spatial_network_name,
        cluster_column = cluster_column,
        number_of_simulations = number_of_simulations,
        set_seed = set_seed,
        seed_number = seed_number
    )

    # combine original and simulated network
    table_sim_results <- sample_dt[, .N, by = c(
        "unified_int", "type_int", "round"
    )]

    ## create complete simulations
    ## add 0 if no single interaction was found
    unique_ints <- unique(table_sim_results[, .(unified_int, type_int)])

    # data.table with 0's for all interactions
    minimum_simulations <- unique_ints[rep(
        seq_len(nrow(unique_ints)), number_of_simulations
    ), ]
    minimum_simulations[, round := rep(
        paste0("sim", seq_len(number_of_simulations)),
        each = nrow(unique_ints)
    )]
    minimum_simulations[, N := 0]

    table_sim_minimum_results <- rbind(table_sim_results, minimum_simulations)
    table_sim_minimum_results[, V1 := sum(N), by = c(
        "unified_int", "type_int", "round"
    )]
    table_sim_minimum_results <- unique(
        table_sim_minimum_results[, .(unified_int, type_int, round, V1)]
    )
    table_sim_results <- table_sim_minimum_results


    # data.table variables
    orig <- unified_int <- V1 <- original <- enrichm <- simulations <- NULL

    table_sim_results[, orig := "simulations"]
    spatial_network_annot[, round := "original"]

    table_orig_results <- spatial_network_annot[, .N, by = c(
        "unified_int", "type_int", "round"
    )]
    table_orig_results[, orig := "original"]
    data.table::setnames(table_orig_results, old = "N", new = "V1")

    table_results <- rbind(table_orig_results, table_sim_results)



    # add missing combinations from original or simulations
    # probably not needed anymore
    all_simulation_ints <- as.character(unique(table_results[
        orig == "simulations"
    ]$unified_int))
    all_original_ints <- as.character(unique(table_results[
        orig == "original"
    ]$unified_int))
    missing_in_original <- all_simulation_ints[
        !all_simulation_ints %in% all_original_ints
    ]
    missing_in_simulations <- all_original_ints[
        !all_original_ints %in% all_simulation_ints
    ]
    create_missing_for_original <- table_results[
        unified_int %in% missing_in_original
    ]
    create_missing_for_original <- unique(create_missing_for_original[
        , c("orig", "V1") := list("original", 0)
    ])
    create_missing_for_simulations <- table_results[
        unified_int %in% missing_in_simulations
    ]
    create_missing_for_simulations <- unique(
        create_missing_for_simulations[, c("orig", "V1") := list(
            "simulations", 0
        )]
    )

    table_results <- do.call(
        "rbind",
        list(
            table_results, create_missing_for_original,
            create_missing_for_simulations
        )
    )


    ## p-values
    combo_list <- rep(NA, length = length(unique(table_results$unified_int)))
    p_high <- rep(NA, length = length(unique(table_results$unified_int)))
    p_low <- rep(NA, length = length(unique(table_results$unified_int)))

    for (int_combo in seq_along(unique(table_results$unified_int))) {
        this_combo <- as.character(unique(table_results$unified_int)[int_combo])

        sub <- table_results[unified_int == this_combo]

        orig_value <- sub[orig == "original"]$V1
        sim_values <- sub[orig == "simulations"]$V1

        length_simulations <- length(sim_values)
        if (length_simulations != number_of_simulations) {
            additional_length_needed <- number_of_simulations -
                length_simulations
            sim_values <- c(sim_values, rep(0, additional_length_needed))
        }

        p_orig_higher <- 1 - (sum((orig_value + 1) > (sim_values + 1)) /
            number_of_simulations)
        p_orig_lower <- 1 - (sum((orig_value + 1) < (sim_values + 1)) /
            number_of_simulations)

        combo_list[[int_combo]] <- this_combo
        p_high[[int_combo]] <- p_orig_higher
        p_low[[int_combo]] <- p_orig_lower
    }
    res_pvalue_DT <- data.table::data.table(
        unified_int = as.vector(combo_list),
        p_higher_orig = p_high,
        p_lower_orig = p_low
    )


    # depletion or enrichment in barplot format
    table_mean_results <- table_results[, .(mean(V1)), by = c(
        "orig", "unified_int", "type_int"
    )]
    table_mean_results_dc <- data.table::dcast.data.table(
        data = table_mean_results, formula = type_int + unified_int ~ orig,
        value.var = "V1"
    )
    table_mean_results_dc[, original := ifelse(is.na(original), 0, original)]
    table_mean_results_dc[, enrichm := log2((original + 1) / (simulations + 1))]


    table_mean_results_dc <- merge(
        table_mean_results_dc, res_pvalue_DT,
        by = "unified_int"
    )
    data.table::setorder(table_mean_results_dc, enrichm)
    table_mean_results_dc[, unified_int := factor(unified_int, unified_int)]

    # adjust p-values for mht

    # data.table variables
    p.adj_higher <- p.adj_lower <- p_lower_orig <- p_higher_orig <-
        PI_value <- int_ranking <- NULL

    table_mean_results_dc[, p.adj_higher := stats::p.adjust(
        p_higher_orig,
        method = sel_adjust_method
    )]
    table_mean_results_dc[, p.adj_lower := stats::p.adjust(
        p_lower_orig,
        method = sel_adjust_method
    )]


    table_mean_results_dc[, PI_value := ifelse(p.adj_higher <= p.adj_lower,
        -log10(p.adj_higher + (1 / number_of_simulations)) * enrichm,
        -log10(p.adj_lower + (1 / number_of_simulations)) * enrichm
    )]
    data.table::setorder(table_mean_results_dc, PI_value)

    # order
    table_mean_results_dc <- table_mean_results_dc[order(-PI_value)]
    table_mean_results_dc[, int_ranking := seq_len(.N)]

    return(list(
        raw_sim_table = table_results,
        enrichm_res = table_mean_results_dc
    ))
}

prox.results.custom <- cellProxEnrich.cust(sln.sm, cluster_column = 'L1.annot', adjust_method = "fdr",
                                      number_of_simulations = 200, spatial_network_name = "knn_network")
cellProximityBarplot(sln.sm, CPscore = prox.results.custom,  min_orig_ints = 3, min_sim_ints = 3, return_plot = T)
```


