---
title: "R Notebook"
output: html_notebook
---


```{r}
# BiocManager::install("fgsea")
# remotes::install_github('JEFworks-Lab/STdeconvolve')
library(STdeconvolve)
library(Giotto)
```


```{r readRDS-excl-1}
sln <- readRDS("sln.clustering2.res0.5.20250411.1611.RDS")

```


```{r subsample-restrictCorpus}
md <- pDataDT(sln)
keepCells <- subset(md, cell_ID %in% sample(md$cell_ID, 1e6))$cell_ID
sln.sm <- subsetGiotto(gobject = sln, cell_ids = keepCells)
md <- pDataDT(sln.sm)
pos <- data.frame(x = sln.sm@spatial_locs$cell$raw$sdimx, y=sln.sm@spatial_locs$cell$raw$sdimy, 
                  row.names = sln.sm@spatial_locs$cell$raw$cell_ID) ## x and y positions of each pixel
cd <- Giotto::getExpression(sln.sm, output = "matrix")
annot <- md$L1.annot
counts <- cleanCounts(counts = cd, verbose = TRUE)
counts <- round(counts)  # need integer values so round off
corpus <- restrictCorpus(counts, removeAbove = 30.0, removeBelow = 0.01, alpha = 1, plot = TRUE,verbose = TRUE)
# corpus <- counts
```


```{r fit-LDA}
# ldas <- fitLDA(t(as.matrix(corpus)), Ks = seq(61, 63, by = 1),perc.rare.thresh = 0.05, plot=TRUE, verbose=TRUE, 
#                ncores = parallel::detectCores())
ldas <- fitLDA(t(as.matrix(corpus)), Ks = 62, perc.rare.thresh = 0.05, plot=TRUE, verbose=TRUE, 
               ncores = parallel::detectCores())
```


# save state
```{r save-LDA}
filename <- paste0("STdeconvolve.ldas.sln.clustering2.res0.5.20250411.1611.RDS")
saveRDS(ldas, filename)

```


```{r optLA}
## select model with minimum perplexity
optLDA <- optimalModel(models = ldas, opt = 62)

## extract pixel cell-type proportions (theta) and cell-type gene expression profiles (beta) for the given dataset
## we can also remove cell-types from pixels that contribute less than 5% of the pixel proportion
## and scale the deconvolved transcriptional profiles by 1000 
results <- getBetaTheta(optLDA, perc.filt = 0.05, betaScale = 1000)
deconProp <- results$theta;    deconGexp <- results$beta
# vizAllTopics(deconProp, pos, groups = annot,  group_cols = rainbow(length(levels(annot))), r=200, lwd=0.05)
```


```{r plot-correlations-with-clustering}
com <- md$L1.annot # list of cluster identities
com_proxyTheta <- model.matrix(~ 0 + com)
rownames(com_proxyTheta) <- md$cell_ID
colnames(com_proxyTheta) <- unlist(lapply(colnames(com_proxyTheta), 
                                          function(x) { unlist(strsplit(x, "com"))[2]  }))
com_proxyTheta <- as.data.frame.matrix(com_proxyTheta)
com_proxyTheta[1:5,1:5]

corMat_prop <- STdeconvolve::getCorrMtx(m1 = as.matrix(com_proxyTheta), m2 = deconProp, type = "t")
rownames(corMat_prop) <- paste0("trnsfr_leiden", seq(nrow(corMat_prop)))
colnames(corMat_prop) <- paste0("STdeconvolve_", seq(ncol(corMat_prop)))

## order the cell-types rows based on best match (highest correlation) with each community 
pairs <- STdeconvolve::lsatPairs(corMat_prop)
m <- corMat_prop[pairs$rowix, pairs$colsix]

STdeconvolve::correlationPlot(mat = m, colLabs = "L1.annot", rowLabs = "STdeconvolve") +
  ggplot2::theme( axis.text.x = ggplot2::element_text(angle = 90) )
```



```{r save-result-table}
saveRDS(results, "STdeconvolve.results.sln.clustering2.res0.5.20250411.1611.RDS")
```


Job ID: 63001426
Cluster: slurm_cluster
User/Group: heratr01/heratr01
State: OUT_OF_MEMORY (exit code 0)
Nodes: 1
Cores per node: 20
CPU Utilized: 00:09:48
CPU Efficiency: 0.02% of 32-01:43:40 core-walltime
Job Wall-clock time: 1-14:29:11
Memory Utilized: 48.81 GB
Memory Efficiency: 16.27% of 300.00 GB







